/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import com.google.protobuf.TextFormat.ParseException;
import entidades.ClienteEntidad;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.IClienteNegocio;
import negocio.ICuentaNegocio;
import negocio.NegocioException;
import persistencia.ClienteDAO;
import persistencia.ConexionBD;

/**
 *
 * @author Usuario
 */
public class CreacionCuentaInfoForm extends javax.swing.JFrame {

    private IClienteNegocio clienteNegocio;

    /**
     * Creates new form CreacionCuentaInfoForm
     */
    public CreacionCuentaInfoForm(IClienteNegocio clienteNegocio) {
        this.clienteNegocio = clienteNegocio;

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FondoV = new javax.swing.JPanel();
        RegistrarNombrejText1 = new javax.swing.JTextField();
        FechaNtext = new javax.swing.JTextField();
        RegistrarApellidoPajText1 = new javax.swing.JTextField();
        RegistrarApellidoMajText2 = new javax.swing.JTextField();
        FondorResgistrate = new javax.swing.JLabel();
        SiguienteButton1 = new javax.swing.JButton();
        RegistrarDomiciliojText1 = new javax.swing.JTextField();
        NombreUsuariojText = new javax.swing.JTextField();
        RegistrarContraseñajText = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(87, 87, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoV.setBackground(new java.awt.Color(108, 142, 132));
        FondoV.setAutoscrolls(true);

        javax.swing.GroupLayout FondoVLayout = new javax.swing.GroupLayout(FondoV);
        FondoV.setLayout(FondoVLayout);
        FondoVLayout.setHorizontalGroup(
            FondoVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        FondoVLayout.setVerticalGroup(
            FondoVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(FondoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 500));

        RegistrarNombrejText1.setBackground(new java.awt.Color(224, 224, 224));
        RegistrarNombrejText1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RegistrarNombrejText1.setForeground(new java.awt.Color(196, 196, 196));
        RegistrarNombrejText1.setText("Nombre");
        jPanel1.add(RegistrarNombrejText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 150, 30));

        FechaNtext.setBackground(new java.awt.Color(224, 224, 224));
        FechaNtext.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        FechaNtext.setForeground(new java.awt.Color(196, 196, 196));
        FechaNtext.setText("AAAA-MM-DD");
        jPanel1.add(FechaNtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 150, 30));

        RegistrarApellidoPajText1.setBackground(new java.awt.Color(224, 224, 224));
        RegistrarApellidoPajText1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RegistrarApellidoPajText1.setForeground(new java.awt.Color(196, 196, 196));
        RegistrarApellidoPajText1.setText("Primer Apellido");
        jPanel1.add(RegistrarApellidoPajText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 150, 30));

        RegistrarApellidoMajText2.setBackground(new java.awt.Color(224, 224, 224));
        RegistrarApellidoMajText2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RegistrarApellidoMajText2.setForeground(new java.awt.Color(196, 196, 196));
        RegistrarApellidoMajText2.setText("Segundo Apellido");
        jPanel1.add(RegistrarApellidoMajText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 150, 30));

        FondorResgistrate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        FondorResgistrate.setForeground(new java.awt.Color(224, 224, 224));
        FondorResgistrate.setText("Registrate");
        jPanel1.add(FondorResgistrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 200, 100));

        SiguienteButton1.setBackground(new java.awt.Color(108, 142, 132));
        SiguienteButton1.setText("Siguiente");
        SiguienteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(SiguienteButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 100, 30));

        RegistrarDomiciliojText1.setBackground(new java.awt.Color(224, 224, 224));
        RegistrarDomiciliojText1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RegistrarDomiciliojText1.setForeground(new java.awt.Color(196, 196, 196));
        RegistrarDomiciliojText1.setText("Domicilio");
        jPanel1.add(RegistrarDomiciliojText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 150, 30));

        NombreUsuariojText.setBackground(new java.awt.Color(224, 224, 224));
        NombreUsuariojText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        NombreUsuariojText.setForeground(new java.awt.Color(196, 196, 196));
        NombreUsuariojText.setText("Nombre Usuario");
        jPanel1.add(NombreUsuariojText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 150, 30));

        RegistrarContraseñajText.setBackground(new java.awt.Color(224, 224, 224));
        RegistrarContraseñajText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(RegistrarContraseñajText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 150, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Fecha de Nacimiento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarCliente(ClienteEntidad cliente) throws PresentacionException {
        try {
            this.clienteNegocio.agregarCliente(cliente);
            JOptionPane.showMessageDialog(null, "en horabuena, " + cliente.getNombre(), "Se ha registrado con exito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error de registro", JOptionPane.ERROR_MESSAGE);

        }
    }

    private LocalDate convertirFecha(String fecha) {
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate fechalocal = LocalDate.parse(fecha, formato);
        return fechalocal;

    }
    private void SiguienteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteButton1ActionPerformed

        String nombre = RegistrarNombrejText1.getText();
        String contrasena = new String(RegistrarContraseñajText.getPassword());
        String apellidoPa = RegistrarApellidoPajText1.getText();
        String apellidoMa = RegistrarApellidoMajText2.getText();
        String domicilio = RegistrarDomiciliojText1.getText();
        String fechaNacimientoString = FechaNtext.getText();
        String nombreUsuario = NombreUsuariojText.getText();

        LocalDate fechaNacimiento=convertirFecha(fechaNacimientoString);

        ClienteEntidad cliente = new ClienteEntidad(nombre, nombreUsuario, contrasena, apellidoPa, apellidoMa, fechaNacimiento, domicilio);

        try {
            this.RegistrarCliente(cliente);
        } catch (PresentacionException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error de registro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_SiguienteButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FechaNtext;
    private javax.swing.JPanel FondoV;
    private javax.swing.JLabel FondorResgistrate;
    private javax.swing.JTextField NombreUsuariojText;
    private javax.swing.JTextField RegistrarApellidoMajText2;
    private javax.swing.JTextField RegistrarApellidoPajText1;
    private javax.swing.JPasswordField RegistrarContraseñajText;
    private javax.swing.JTextField RegistrarDomiciliojText1;
    private javax.swing.JTextField RegistrarNombrejText1;
    private javax.swing.JButton SiguienteButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
