/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

/**
 *
 * @author Usuario
 */
public class CreacionCuentaForm extends javax.swing.JFrame {

    /**
     * Creates new form CreacionCuentaForm
     */
    public CreacionCuentaForm() {
        initComponents();
        this.setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegistrarUsuariojText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        RegistrarseButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        RegistrarContraseñajText = new javax.swing.JPasswordField();
        ConfirmarContraseñajText = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(87, 87, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistrarUsuariojText.setBackground(new java.awt.Color(224, 224, 224));
        RegistrarUsuariojText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RegistrarUsuariojText.setForeground(new java.awt.Color(196, 196, 196));
        RegistrarUsuariojText.setText("Numero Cuenta");
        RegistrarUsuariojText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarUsuariojTextActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarUsuariojText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(224, 224, 224));
        jLabel1.setText("Crear Cuenta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 200, 100));

        RegistrarseButton.setBackground(new java.awt.Color(108, 142, 132));
        RegistrarseButton.setForeground(new java.awt.Color(224, 224, 224));
        RegistrarseButton.setText("Registrarse");
        RegistrarseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 150, 30));

        jPanel3.setBackground(new java.awt.Color(108, 142, 132));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        RegistrarContraseñajText.setBackground(new java.awt.Color(224, 224, 224));
        RegistrarContraseñajText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RegistrarContraseñajText.setText("Contraseña");
        RegistrarContraseñajText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarContraseñajTextActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarContraseñajText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 150, 30));

        ConfirmarContraseñajText.setBackground(new java.awt.Color(224, 224, 224));
        ConfirmarContraseñajText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ConfirmarContraseñajText.setText("Confirmar Contraseña");
        ConfirmarContraseñajText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarContraseñajTextActionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmarContraseñajText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 150, 30));

        jPanel2.setBackground(new java.awt.Color(108, 142, 132));
        jPanel2.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarUsuariojTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarUsuariojTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarUsuariojTextActionPerformed

    private void RegistrarseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarseButtonActionPerformed

    private void ConfirmarContraseñajTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarContraseñajTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmarContraseñajTextActionPerformed

    private void RegistrarContraseñajTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarContraseñajTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarContraseñajTextActionPerformed

    public int generarNumero() {
        // Generar un número aleatorio de 8 dígitos
        return (int) (Math.random() * 90000000) + 10000000; // Genera un número entre 10000000 y 99999999
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionCuentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionCuentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionCuentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionCuentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionCuentaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmarContraseñajText;
    private javax.swing.JPasswordField RegistrarContraseñajText;
    private javax.swing.JTextField RegistrarUsuariojText;
    private javax.swing.JButton RegistrarseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
