/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import entidades.ClienteEntidad;
import entidades.CuentaEntidad;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import negocio.IClienteNegocio;
import negocio.ICuentaNegocio;
import negocio.NegocioException;

/**
 *
 * @author Usuario
 */
public class ElegirCuentaForm extends javax.swing.JFrame {
    private JComboBox<CuentaEntidad> comboBox;
    private IClienteNegocio clienteNegocio;
    private ICuentaNegocio cuentaNegocio;
    private ClienteEntidad clienteActual;

    /**
     * Creates new form ElegirCuentaForm
     */
    public ElegirCuentaForm(IClienteNegocio clienteNegocio, ICuentaNegocio cuentaNegocio, ClienteEntidad clienteActual) {
        this.clienteNegocio = clienteNegocio;
        this.cuentaNegocio = cuentaNegocio;
        this.clienteActual = clienteActual;
        initComponents();
        llenarComboBox();
    }

    private void llenarComboBox() {
        DefaultComboBoxModel<CuentaEntidad> comboBoxCuentas = new DefaultComboBoxModel<>();
        List<CuentaEntidad> cuentas = null;
        try {
            cuentas = this.cuentaNegocio.obtenerTodasLasCuentas(clienteActual);
            
        } catch (NegocioException ex) {
            Logger.getLogger(ElegirCuentaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (CuentaEntidad numeroCuenta : cuentas) {
            comboBoxCuentas.addElement(numeroCuenta);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FondorResgistrate = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(87, 87, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondorResgistrate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        FondorResgistrate.setForeground(new java.awt.Color(224, 224, 224));
        FondorResgistrate.setText("Seleccione la Cuenta");
        jPanel1.add(FondorResgistrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 230, 100));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 250, 40));

        jButton1.setBackground(new java.awt.Color(108, 142, 132));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jPanel2.setBackground(new java.awt.Color(108, 142, 132));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondorResgistrate;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
