/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import entidades.ClienteEntidad;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import persistencia.ClienteDAO;
import persistencia.ConexionBD;
import persistencia.PersistenciaException;

/**
 *
 * @author Usuario
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(this);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        InicioSesion = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        txtRegistro = new javax.swing.JLabel();
        Contraseña = new javax.swing.JPasswordField();
        btnLoggin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        NombreUsuariojText = new javax.swing.JTextField();
        RetirarSinCuentaButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(108, 142, 132));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(87, 87, 86));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InicioSesion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        InicioSesion.setForeground(new java.awt.Color(224, 224, 224));
        InicioSesion.setText("Iniciar Sesión");
        jPanel2.add(InicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 200, 100));

        btnRegistrarse.setBackground(new java.awt.Color(108, 142, 132));
        btnRegistrarse.setForeground(new java.awt.Color(224, 224, 224));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 150, 30));

        txtRegistro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRegistro.setForeground(new java.awt.Color(224, 224, 224));
        txtRegistro.setText("¿No estas registrado? Registra una cuenta:");
        jPanel2.add(txtRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        Contraseña.setBackground(new java.awt.Color(224, 224, 224));
        Contraseña.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, 30));

        btnLoggin.setBackground(new java.awt.Color(108, 142, 132));
        btnLoggin.setForeground(new java.awt.Color(224, 224, 224));
        btnLoggin.setText("Login");
        btnLoggin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLoggin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 150, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Contraseña");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        NombreUsuariojText.setBackground(new java.awt.Color(224, 224, 224));
        NombreUsuariojText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        NombreUsuariojText.setForeground(new java.awt.Color(196, 196, 196));
        NombreUsuariojText.setText("Nombre Usuario");
        NombreUsuariojText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreUsuariojTextMouseClicked(evt);
            }
        });
        jPanel2.add(NombreUsuariojText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 150, 30));

        RetirarSinCuentaButton.setBackground(new java.awt.Color(102, 102, 102));
        RetirarSinCuentaButton.setText("Retirar Sin Cuenta");
        RetirarSinCuentaButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RetirarSinCuentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarSinCuentaButtonActionPerformed(evt);
            }
        });
        jPanel2.add(RetirarSinCuentaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 180, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 440, 530));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        CreacionCuentaInfoForm registrarse = new CreacionCuentaInfoForm();
        registrarse.setVisible(true);
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnLogginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogginActionPerformed
// Obtener el nombre de usuario y la contraseña ingresados por el usuario
       
    }//GEN-LAST:event_btnLogginActionPerformed

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaActionPerformed

    private void NombreUsuariojTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreUsuariojTextMouseClicked
        NombreUsuariojText.setText("");
    }//GEN-LAST:event_NombreUsuariojTextMouseClicked

    private void RetirarSinCuentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarSinCuentaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RetirarSinCuentaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JLabel InicioSesion;
    private javax.swing.JTextField NombreUsuariojText;
    private javax.swing.JButton RetirarSinCuentaButton;
    private javax.swing.JButton btnLoggin;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtRegistro;
    // End of variables declaration//GEN-END:variables
}
